export const MenuData = [
    {
      title: 'Home',
      url: '/',
      cName: 'nav-links',
      icon: 'fa-solid fa-house-user',
    },
    {
      title: 'Chi sono',
      url: '/chi-sono',
      cName: 'nav-links',
    },
    {
      title: 'Blog',
      url: '/blog',
      cName: 'nav-links',
    },
    {
      title: 'Contatti',
      url: '/contatti',
      cName: 'nav-links',
      icon: 'fa-solid fa-house-user',
    },
  ]
  
  export const SliderData = [
    {
      id: 1,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 1',
      subtitle: 'Subtitle 1',
      link: '#',
    },
    {
      id: 2,
      image: 'https://images.pexels.com/photos/1438761/pexels-photo-1438761.jpeg',
      title: 'Title 2',
      subtitle: 'Subtitle 2',
    },
    {
      id: 3,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 3',
      subtitle: 'Subtitle 3',
    },
    {
      id: 4,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 4',
      subtitle: 'Subtitle 4',
      link: '#',
    },
    {
      id: 5,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 5',
      subtitle: 'Subtitle 5',
      link: '#',
    },
  ]
  
  export const ItemData = [
    {
      id: 1,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 1',
      subtitle: 'Subtitle 1',
      link: '#',
      tag: 'blog',
    },
    {
      id: 2,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 2',
      subtitle: 'Subtitle 2',
      tag: 'article',
    },
    {
      id: 3,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 3',
      subtitle: 'Subtitle 3',
      tag: 'article',
    },
    {
      id: 4,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 4',
      subtitle: 'Subtitle 4',
      link: '#',
      tag: 'blog',
    },
    {
      id: 5,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 5',
      subtitle: 'Subtitle 5',
      link: '#',
      tag: 'blog',
    },
    {
      id: 6,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 6',
      subtitle: 'Subtitle 6',
      link: '#',
      tag: 'article',
    },
    {
      id: 7,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 7',
      subtitle: 'Subtitle 7',
      tag: 'blog',
    },
    {
      id: 8,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 8',
      subtitle: 'Subtitle 8',
      tag: 'blog',
    },
    {
      id: 9,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 9',
      subtitle: 'Subtitle 9',
      link: '#',
      tag: 'blog',
    },
    {
      id: 10,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 10',
      subtitle: 'Subtitle 10',
      link: '#',
      tag: 'article',
    },
    {
      id: 11,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 11',
      subtitle: 'Subtitle 11',
      link: '#',
      tag: 'article',
    },
    {
      id: 12,
      image: 'https://images.pexels.com/photos/797797/pexels-photo-797797.jpeg',
      title: 'Title 12',
      subtitle: 'Subtitle 12',
      link: '#',
      tag: 'article',
    },
  ]
  